[package]
name = "example"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]
spike-rs = { path = "../" }

[lib]
name = "example"
crate-type = ["cdylib"]
